/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-15 14:06:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Welcome To Login</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function myvalidate(){\r\n");
      out.write("\tvar accountno=document.myform.acno.value;\r\n");
      out.write("\tvar password=document.myform.pw.value;\r\n");
      out.write("\tif(accountno==\"\" || password==\"\"){\r\n");
      out.write("\t\talert(\"AccountNo  and password are should not be empty\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"login.jpg\">\r\n");
      out.write("<center>\r\n");
      out.write("<FORM  name=\"myform\" method=\"POST\" ACTION=\"login.do\">\r\n");
      out.write("<center><h1><marquee>WELCOME TO SBI</marquee></h1></center>\r\n");
      out.write("<TABLE>\r\n");
      out.write("<TR>\r\n");
      out.write("\t<TD>AccountNo:</TD>\r\n");
      out.write("\t<TD><INPUT TYPE=\"text\" NAME=\"acno\"></TD>\r\n");
      out.write("</TR>\r\n");
      out.write("<TR>\r\n");
      out.write("\t<TD>Password:</TD>\r\n");
      out.write("\t<TD><INPUT TYPE=\"password\"  name=\"pw\"></TD>\r\n");
      out.write("</TR>\r\n");
      out.write("<TR>\r\n");
      out.write("\t<TD></TD>\r\n");
      out.write("\t<TD><INPUT TYPE=\"submit\" name=\"submit\"value=\"Login\" onclick=\"return myvalidate()\">&nbsp;&nbsp;<br><br><a href=\"Registration.jsp\">Not yet registered Register Here</a></TD>\r\n");
      out.write("\t\r\n");
      out.write("</TR>\r\n");
      out.write("\r\n");
      out.write("</TABLE>\r\n");
      out.write("</FORM>\r\n");
      out.write("<h1><font color=\"Blue\" size=\"10\"> </font></h1>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<font color=\"Red\">\r\n");
 String ref= (String)request.getAttribute("msg");
      out.write('\r');
      out.write('\n');
 if(ref!=null){

      out.write('\r');
      out.write('\n');
      out.print(ref );
      out.write('\r');
      out.write('\n');
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</font>\r\n");
      out.write("</center>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
