/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-15 14:06:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Registration</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction myvalid() {\r\n");
      out.write("\t\tvar fname = document.reg.fn.value;\r\n");
      out.write("\t\tvar lname = document.reg.ln.value;\r\n");
      out.write("\t\tvar phoneno = document.reg.mn.value;\r\n");
      out.write("\t\tvar add = document.reg.add.value;\r\n");
      out.write("\t\tvar dob = document.reg.db.value;\r\n");
      out.write("\t\tvar pass1 = document.reg.pwd.value;\r\n");
      out.write("\t\tvar pass2 = document.reg.pwd1.value;\r\n");
      out.write("\t\tvar amt = document.reg.en.value;\r\n");
      out.write("\t\tif (fname == \"\") {\r\n");
      out.write("\t\t\talert(\"first name should not be empty\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (lname == \"\") {\r\n");
      out.write("\t\t\talert(\"last name should not be empty\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (phoneno == \"\") {\r\n");
      out.write("\t\t\talert(\"phone number should not be empty\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t\t} else if (add == \"\") {\r\n");
      out.write("\t\t\talert(\"Address should not be empty\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (dob == \"\") {\r\n");
      out.write("\t\t\talert(\"Date of Birth should not be empty\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (pass1 == \"\") {\r\n");
      out.write("\t\t\talert(\"password should not be empty\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (pass2 == \"\") {\r\n");
      out.write("\t\t\talert(\"retype password should not be empty\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (pass1 != pass2) {\r\n");
      out.write("\t\t\talert(\"retype password should be matched with password\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body background=\"login.jpg\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t<marquee>WELCOME TO ONLINE REGISTRATION OF SBI</marquee>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t<FORM name=\"reg\" METHOD=\"POST\" ACTION=\"reg.do\">\r\n");
      out.write("\t\t\t<TABLE>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>FirstName:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"text\" NAME=\"fn\"></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>LastName:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"text\" NAME=\"ln\"></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>MobileNo:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"text\" NAME=\"mn\"></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>Address:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><TEXTAREA NAME=\"add\" ROWS=\"\" COLS=\"\"></TEXTAREA></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>DOB:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"Date\" NAME=\"db\"></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>Gender:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"radio\" NAME=\"m\" value=\"male\">Male<INPUT\r\n");
      out.write("\t\t\t\t\t\tTYPE=\"radio\" NAME=\"m\" value=\"female\">Female</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>Type of Account:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"radio\" NAME=\"acctype\" value=\"sb\">SB<INPUT\r\n");
      out.write("\t\t\t\t\t\tTYPE=\"radio\" NAME=\"acctype\" value=\"fd\">FD<BR> <INPUT\r\n");
      out.write("\t\t\t\t\t\tTYPE=\"radio\" NAME=\"acctype\" value=\"ca\">CA<INPUT\r\n");
      out.write("\t\t\t\t\t\tTYPE=\"radio\" NAME=\"acctype\" value=\"rd\">RD<BR></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Enter the Amount (minimum 1000 Rs)</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"en\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>PASSWORD:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"password\" name=\"pwd\"></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>RE-TYPE PASSWORD:</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT TYPE=\"password\" name=\"pwd1\"></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" name=\"submit\" value=\"Register\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"return myvalid()\"> &nbsp;&nbsp;&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\ttype=\"reset\" value=\"RESET\"><br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<a href=\"login.jsp\">Already Registered Login</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</FORM>\r\n");
      out.write("\t\t");

			String errormsg = (String) request.getAttribute("msg");
			if (errormsg != null) {
		
      out.write("\r\n");
      out.write("\t\t<font>");
      out.print(errormsg);
      out.write(" </font>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
